# Generated by Django 4.2.7 on 2023-11-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(db_index=True, max_length=100, verbose_name='Автор')),
                ('birthday', models.DateTimeField(auto_now_add=True, verbose_name='День рождение')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Авторы',
                'verbose_name_plural': 'Автор',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100, unique=True, verbose_name='Название книги')),
                ('date_publish', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('quantity_page', models.IntegerField(default=0, verbose_name='Количество страниц ')),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=100, verbose_name='Международный стандартный книжный номер')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книга',
                'db_table': 'books',
                'db_table_comment': 'Question answers',
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(db_column='Жанр', max_length=100, unique=True, verbose_name='Жанр')),
                ('description', models.TextField(db_column='Описание ', verbose_name='Описание ')),
            ],
            options={
                'verbose_name': 'Жанры',
                'verbose_name_plural': 'Жаныр',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Publisher', models.CharField(max_length=100, verbose_name='Название издательства')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100, verbose_name='Название издательства')),
                ('age', models.IntegerField(default=0, verbose_name='возрост ')),
            ],
            options={
                'verbose_name': 'читатели',
                'verbose_name_plural': 'читатель',
                'db_table': 'reader',
            },
        ),
        migrations.AddConstraint(
            model_name='reader',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 5)), name='age_gte_5'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='books.author', verbose_name='Автор'),
        ),
    ]
